### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by AnkitDhiman2**

### CODE REVIEW

**Comment by 40010753** [comment]
Your header file has my Name as the author. You can change it to yours.
You can add Automated workflows for build, test and analyze.

**Review by 40010753 — CHANGES_REQUESTED** [review]
Use the MD file syntax to add link to your name as per below:
* Solution by [ Your name ] (link) without spaces between braces and brackets.

**Comment by AnkitDhiman2** [comment]
Changes made:

- Added link to solution using MD file syntax

**Review by AnkitDhiman2 — COMMENTED** [review]
Added link to solution using MD file syntax

**Review by 40010753 — APPROVED** [review]

**Pull request merged**
